version: "3.8"
services:
  mysqldb:
    container_name: mysqldb
    build: ./mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: *
      MYSQL_DATABASE: *
  backend:
    container_name: app_backend
    build: 
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment: 
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3065:3065
    links:
      - mysqldb
    depends_on:
      - mysqldb
    restart: always
  frontend:
    container_name: app_frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:   
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3060:3060
    stdin_open: true